# Generated by Django 3.0.5 on 2020-11-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Query', '0003_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='flat',
            field=models.CharField(default='flat', max_length=200),
        ),
    ]
